#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

ping() {
  echo Pong from taskfile
  echo args: "$1" "$2" "$3"
}

buildMicrobundle5() {
  set -x
  rm -rfv dist
  dts-bundle-generator --no-banner --project tsconfig.build.json -o dist/index.d.ts src/index.ts
  microbundle -i src/index.ts --tsconfig tsconfig.build.json --no-generateTypes --no-sourcemap --no-compress --target node -f esm -o dist
  name=$(cat package.json | jq -r '.name')
  cp -v README.md package.json dist
  cd dist
  mv index.d.ts "$name.d.ts"
  cat ../package.json | jq --arg name "$name" '
    .module = "./\($name).mjs" |
    .types = "./\($name).d.ts" |
    .exports.".".default = "./\($name).mjs"
  ' > package.json
  cd ..
  set +x
}

build_cp() {
  set -x
  rm -rfv dist
  mkdir dist
  cp -rfv index.js dist
  cp -fv README.md package.json dist
  set +x
}

"$@"
